[package]
name = "goofi-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
goofi-supervisor = { path = "../goofi-supervisor" }
goofi-core = { path = "../goofi-core" }
goofi-node = { path = "../goofi-node" }
goofi-host-sdk = { path = "../goofi-host-sdk" }
goofi-codec = { path = "../goofi-codec" }
goofi-transport = { path = "../goofi-transport" }
indexmap = "2"
